#/home/data/aicity/byclass_224/1/
#### general settings
name: MYNET
use_tb_logger: true

#### datasets
datasets:
  name: CADP
  train: /home/data/aicity/byclass_320/Train
  valid: /home/data/aicity/byclass_320/Validation
  test: /home/data/aicity/test_224
  stride: 1

  #train: /home/data/jinyoung/Server/Demo/Train/
  #valid: /home/data/jinyoung/Server/Demo/Test/
  #test: /home/data/jinyoung/Server/Demo/Test/
dataloader:
  train:
    batch_size: 8
    shuffle: true
    # pin_memeory: true
    num_workers: 24

  valid:
    batch_size: 8
    shuffle: true
    # pin_memeory: true
    num_workers: 24

  test:
    batch_size: 1
    shuffle: false
    num_workers: 24

#### network structures
MYNET:
  sequence_size: 31 # Temporal duration of input clips

#### training settings: learning rate scheme, loss
trainer:
  epochs: 1000
  device: 1
  save_path: /home/data/aicity/weight/
  #ckpt_path: ckpt/eff_noatt.pt
  comment: no comment
    
tester:
  ckpt_path: /home/data/aicity/weight/CADP/03April_0145/ckpt/best.pt
  device: 0


criterion:
  name: CrossEntropy

optimizer:
  name: Adam   ### Adam, RMSprop, SGD
  lr: !!float 1e-3
  # betas: (0.9, 0.999)
  eps: !!float 1e-8
  weight_decay: !!float 1e-6


#### scheduler settings
scheduler:
  name: cycle
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5